# Generated by Django 4.0.5 on 2022-06-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idboleta', models.IntegerField()),
                ('nombreProd', models.CharField(max_length=30)),
                ('detalle', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('valor', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcliente', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('registro', models.BooleanField()),
                ('correoCliente', models.EmailField(max_length=254)),
            ],
        ),
    ]
