# Generated by Django 4.0.5 on 2022-06-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_boleta_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='correoProveedor',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='fechaIncorporacion',
        ),
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=b'I01\n', null=True, upload_to='static\\IMAGENES'),
        ),
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
