# Generated by Django 4.0.5 on 2022-06-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_productos_correoproveedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('suscripcion', models.BooleanField()),
                ('logueado', models.BooleanField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='IMAGENES'),
        ),
    ]
